version: '3.8'

services:
  consulting-chatbot:
    container_name: consulting-chatbot
    build:
      context: .
      dockerfile: Dockerfile
    image: consulting-chatbot
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/consulting-chatbot